# Generated by Django 6.0.2 on 2026-03-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ledger.recipe'),
        ),
    ]
